apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-webui
  template:
    metadata:
      labels:
        app: stable-diffusion-webui
    spec:
      runtimeClassName: nvidia
      initContainers:
      - name: download-model
        image: alpine:3.12
        command: ['sh', '-c', 'if [ ! -e "/models/sd-v1-4.ckpt" ]; then wget https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt -P /models; fi']
        volumeMounts:
        - name: model-data
          mountPath: /models
      containers:
      - name: stable-diffusion-webui
        image: ghcr.io/matthew-graves/stable-diffusion-webui-k8s:main
        imagePullPolicy: Always
        volumeMounts:
        - name: model-data
          mountPath: /models
      volumes:
      - name: model-data
        hostPath:
          path: /models